# Generated by Django 2.2.19 on 2021-04-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EMAIL_RECIEPIENT", models.EmailField(max_length=254)),
                ("EMAIL_SUBJECT", models.CharField(max_length=50, null=True)),
                ("EMAIL_BODY", models.TextField(null=True)),
                (
                    "EMAIL_ATTACHMENT",
                    models.FileField(null=True, upload_to="attachments"),
                ),
            ],
        ),
    ]
