# Generated by Django 2.2.19 on 2021-04-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("send_emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="EMAIL_ATTACHMENT",
            field=models.FileField(blank=True, null=True, upload_to="attachments"),
        ),
    ]
