# Generated by Django 2.2.19 on 2021-05-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_emails', '0003_auto_20210504_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesent',
            name='SENT',
            field=models.BooleanField(default=True),
        ),
    ]
