# Generated by Django 2.2.19 on 2021-05-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('send_emails', '0004_messagesent_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='SCHEDULE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.CrontabSchedule'),
        ),
    ]
