# Generated by Django 2.2.19 on 2021-05-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_emails', '0005_message_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='CAMPAIGN',
            field=models.BooleanField(default=False),
        ),
    ]
