# Generated by Django 2.2.19 on 2021-05-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_emails', '0006_message_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='CAMPAIGN_NAME',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
