# Generated by Django 2.2.19 on 2021-05-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_emails', '0007_message_campaign_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='CAMPAIGN_NAME',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
